import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/ThemeProvider"
import SideBar from '@/components/SideBar'
import Provider from '@/Providers/Provider'
import { Suspense } from 'react'
import Loading from './loading'


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
export const metadata: Metadata = {
  title: 'E-STORE',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable}`}>
        <ThemeProvider attribute='class' defaultTheme='Dark'>
          <Provider>
            <main className={`${inter.variable} flex h-screen`}>
              <SideBar />
              {children}
            </main>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  )
}
